<?php

namespace MediaWiki\Extension\SimpleBlogPage\QueryStore;

use Wikimedia\Rdbms\ILoadBalancer;

class Reader extends \MWStake\MediaWiki\Component\DataStore\Reader {

	/**
	 * @var ILoadBalancer
	 */
	private $lb;

	/**
	 * @param ILoadBalancer $lb
	 */
	public function __construct( ILoadBalancer $lb ) {
		parent::__construct();
		$this->lb = $lb;
	}

	public function getSchema() {
		return new BlogEntryQuerySchema();
	}

	protected function makePrimaryDataProvider( $params ) {
		return new PrimaryProvider(
			$this->lb->getConnection( DB_REPLICA ),
			$this->getSchema()
		);
	}

	protected function makeSecondaryDataProvider() {
		// TODO: Implement makeSecondaryDataProvider() method.
	}

	public function read( $params ) {
		return parent::read( $params ); // TODO: Change the autogenerated stub
	}
}